---
# roles/deploy/tasks/main.yml

- name: Install git
  apt:
    pkg: git
    state: present
    update_cache: yes

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
    update_cache: yes

- name: Install npm
  apt:
    pkg: npm
    state: present
    update_cache: yes

- name: Create www directory
  file:
    path: /srv/www
    owner: ubuntu
    group: ubuntu
    state: directory

- name: Clone repository
  git:
    repo: "https://github.com/atplanet/hello-world-express-app.git"
    dest: /srv/www/webapp
    version: master

- name: Install Node Express, locally to the webapp
  npm:
    name: express
    state: present
    path: /srv/www/webapp

- name: Install upstart script, for the webapp
  copy:
    src: upstart.conf
    dest: /etc/init/webapp.conf

- name: Enable and start the webapp service
  service:
    name: webapp
    enabled: yes
    state: restarted

- name: Install Nginx
  apt:
    pkg: nginx
    state: present

- name: Configure Nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/default

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
