---
# roles/build-ami/tasks/main.yml

# this is used later in other steps
# - name: Generate app_time
  # set_fact:
    # app_time: "{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"

- name: Create AMI
  ec2_ami:
    name: "{{ app_prefix }}-ami-{{ app_time }}"
    region: "{{ region }}"
    instance_id: "{{ ec2_id }}"
    wait: yes
    state: present
  register: ami
