---
# roles/launch-ec2/tasks/main.yml

# http://docs.ansible.com/ansible/ec2_ami_find_module.html
- name: Search for the latest Ubuntu 14.04 AMI
  ec2_ami_find:
    region: "{{ region }}"
    name: "ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"
    owner: 099720109477
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result

# http://docs.ansible.com/ansible/ec2_module.html
- name: Launch new EC2 instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ security_groups }}"
    image: "{{ ami_result.results[0].ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

# http://docs.ansible.com/ansible/add_host_module.html
- name: Add new EC2 instances to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ name }}"
    ec2_id: "{{ item.id }}"
  with_items: "{{ec2.instances}}"

# http://docs.ansible.com/ansible/wait_for_module.html
- name: Wait for EC2 instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 120
    timeout: 540
    state: started
  with_items: "{{ec2.instances}}"
