---
# roles/delete-old-lc/tasks/main.yml

- name: Retrieve a list of Auto Scaling Groups, with the app_prefix
  ec2_asg_facts:
    region: "{{ region }}"
    name_regex: "{{ app_prefix }}-.*"
    sort: yes
    sort_start: 0
  register: old_asg_results

- debug: var=old_asg_results

- name: Delete the old Auto Scaling Groups
  ec2_asg:
    region: "{{ region }}"
    name: "{{ item.name }}"
    state: absent
  with_items: old_asg_results.results
  ignore_errors: yes
